spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/rest-web/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true

